---
# File: download.yml - Download tasks for Consul
- name: Read package checksum file
  stat:
    path: "{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  become: false
  vars:
    ansible_become: false
  run_once: true
  register: consul_checksum
  tags: installation
  delegate_to: 127.0.0.1

- name: Download package checksum file
  get_url:
    url: "{{ consul_checksum_file_url }}"
    dest: "{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  become: false
  vars:
    ansible_become: false
  run_once: true
  tags: installation
  when: not consul_checksum.stat.exists | bool
  delegate_to: 127.0.0.1

- name: Read package checksum
  shell: grep "{{ consul_pkg }}" "{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS" | awk '{print $1}'
  become: false
  vars:
    ansible_become: false
  register: consul_sha256
  tags:
    - installation
    - skip_ansible_lint
  delegate_to: 127.0.0.1

- name: Check Consul package file
  stat:
    path: "{{ role_path }}/files/{{ consul_pkg }}"
  become: false
  vars:
    ansible_become: false
  register: consul_package
  tags: installation
  delegate_to: 127.0.0.1

- name: Download Consul package
  get_url:
    url: "{{ consul_zip_url }}"
    dest: "{{ role_path }}/files/{{ consul_pkg }}"
    checksum: "sha256:{{ consul_sha256.stdout }}"
    timeout: "42"
  become: false
  vars:
    ansible_become: false
  tags: installation
  when: not consul_package.stat.exists | bool
  delegate_to: 127.0.0.1
