---
# Gathers facts (bind address) from servers not currently targeted.
# 'delegate_facts' is currently rather buggy in Ansible so this might not
# always work. Hence 'consul_gather_server_facts' defaults to 'no'.
- name: Gather facts from other servers
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ consul_servers | difference(play_hosts) }}"
  ignore_errors: true
  when: consul_gather_server_facts | bool

- name: Expose advertise_address(_wan) datacenter and node_role as facts
  set_fact:
    consul_advertise_address_wan: "{{ consul_advertise_address_wan }}"
    consul_advertise_address: "{{ consul_advertise_address }}"
    consul_bind_address: "{{ consul_bind_address }}"
    consul_datacenter: "{{ consul_datacenter }}"
    consul_node_role: "{{ consul_node_role }}"

- name: Read bootstrapped state
  stat:
    path: "{{ consul_bootstrap_state }}"
  register: bootstrap_state
  ignore_errors: true
  tags: always

- name: Check for gossip encryption key on previously bootstrapped server
  slurp:
    src: "{{ consul_config_path }}/config.json"
  register: consul_config_b64
  ignore_errors: true

- name: Deserialize existing configuration
  set_fact:
    consul_config: "{{ consul_config_b64.content | b64decode | from_json }}"
  when: consul_config_b64.content is defined

- name: Save gossip encryption key from existing configuration
  set_fact:
    consul_raw_key: "{{ consul_config.encrypt }}"
  when: consul_config is defined
