---
# File: install.yml - package installation tasks for Consul

- name: Install OS packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ consul_os_packages }}"
  tags: installation

- name: Update Alpine Package Manager (APK)
  apk:
    update_cache: true
  run_once: true
  when: ansible_os_family == "Alpine"
  delegate_to: 127.0.0.1

- name: Create Temporary Directory for Extraction
  file:
    state: directory
    path: "/tmp/ansible-consul"
  become: false
  tags: installation
  delegate_to: 127.0.0.1

- name: Unarchive Consul package
  unarchive:
    src: "{{ role_path }}/files/{{ consul_pkg }}"
    dest: "/tmp/ansible-consul/"
    creates: "/tmp/ansible-consul/consul"
  become: false
  vars:
    ansible_become: false
  tags: installation
  delegate_to: 127.0.0.1

- name: Install Consul
  copy:
    src: "/tmp/ansible-consul/consul"
    dest: "{{ consul_bin_path }}/consul"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
  tags: installation

- name: Daemon reload systemd in case the binaries upgraded
  systemd: daemon_reload=yes
  become: true
  notify: restart consul
  when:
    - ansible_service_mgr == "systemd"
    - consul_install_upgrade

- name: Cleanup
  file:
    path: "/tmp/ansible-consul"
    state: "absent"
  become: false
  vars:
    ansible_become: false
  tags: installation
  delegate_to: 127.0.0.1
