---
- name: Create directories on Windows
  win_file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ consul_config_path }}"
    - "{{ consul_configd_path }}"
    - "{{ consul_data_path }}"
    - "{{ consul_log_path }}"
    - "{{ consul_bin_path }}"
  when: ansible_os_family == 'Windows'
