---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: vmware_desktop
lint:
  name: yamllint
platforms:
  - name: instance
    box: centos/7
provisioner:
  name: ansible
  inventory:
    hosts:
      consul_instances:
        hosts:
          instance:
        vars:
          foo: hello
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
